---

- hosts: all
  sudo: True

  roles:
     - { role: mesos }
     - { role: marathon }
     - { role: docker }

  tasks:
    - name: sane hosts file
      lineinfile: dest=/etc/hosts regexp='.*{{ inventory_hostname }}$' line="{{ bind }} {{ inventory_hostname }}" state=present
      when: bind is defined
